#!/usr/bin/env sh

WIDTH=${WIDTH}
HEIGHT=${HEIGHT}
DATEFMT=${DATEFMT:-"+%a %d.%m.%Y %H:%M:%S"}
SHORTFMT=${SHORTFMT:-"+%b%d %H:%M"}

OPTIND=1
while getopts ":f:W:H:" opt; do
    case $opt in
        f) DATEFMT="$OPTARG" ;;
        W) WIDTH="$OPTARG" ;;
        H) HEIGHT="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

case "$BLOCK_BUTTON" in
  1|2|3) 

    resolution=`xrandr | grep \* | cut -d' ' -f4`
    arr=(${resolution//x/ })
    resX=arr[0]
    resY=arr[1]

    posX=$(($BLOCK_X - 10))
    offsetX=0
    distanceBetweenPointAndScreenEndX=$(($resX - $BLOCK_X))

    if (($distanceBetweenPointAndScreenEndX - $WIDTH < 0)); then
        offsetX=$(($WIDTH - $distanceBetweenPointAndScreenEndX))
        posX=$(($BLOCK_X - offsetX - 10))
    fi


	# the position of the upper left corner of the popup
	posY=$(($BLOCK_Y - $HEIGHT - 30))

	i3-msg -q "exec yad --calendar \
        --width=$WIDTH --height=$HEIGHT \
	    --undecorated \
	    --close-on-unfocus --no-buttons \
	    --posx=$posX --posy=$posY \
	    > /dev/null"
esac


# echo "$LABEL $(date "$DATEFMT")"
echo "$LABEL $(date "$SHORTFMT")"
