monitor=DP-1, 1920x1080@144.00, 0x0, 1

workspace = 1,monitor:DP-2
workspace = 2,monitor:DP-2
workspace = 3,monitor:DP-2
workspace = 4,monitor:DP-2
workspace = 5,monitor:DP-2
workspace = 6,monitor:DP-2
workspace = 7,monitor:DP-4
workspace = 8,monitor:DP-2
workspace = 9,monitor:DP-2
workspace = 10,monitor:DP-2

exec = ~/.config/hypr/mouse_sensitivity.sh -0.25

bind = $mainMod, B, exec, [float; size 1530 860; center] $TERMINAL btop # quickly check system usage
